OCTAVENOTE label byte
  DB 0
  DB 52
  DB 52
  DB 52
  DB 52
  DB 52
  DB 52
  DB 52
  DB 52
  DB 52
  DB 52
  DB 52
  DB 52
  DB 56
  DB 56

FNUM label byte
  DB 0
  DB 86
  DB 91
  DB 96
  DB 102
  DB 108
  DB 115
  DB 122
  DB 129
  DB 136
  DB 145
  DB 153
  DB 162
  DB 91
  DB 91

savelet label byte
        db 5
        db 2
        db 3
        db 5
        db 10
        db 12
        db 5
        db 14
        db 10
        db 7
        db 12
        db 10
        db 9 
        db 10
        db 0
        db 0

ajat    label byte
        db 6
        db 6
        db 6
        db 18
        db 6
        db 8
        db 4
        db 24
        db 12
        db 8
        db 4
        db 12
        db 12
        db 12
        db 12
        db 36
